apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  name: data.my.domain
spec:
  latestResourceSchemas:
    - v040424-0844.widgets.data.my.domain
  permissionClaims:
    - group: ""
      resource: "secrets"
      all: true
    - group: ""
      resource: "configmaps"
      all: true
    - group: ""
      resource: "namespaces"
      all: true
